config/routes.rb
Rails.application.routes.draw do
  resources :listings

  resources :users, only: [:new]

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/signin' => 'sessions#new', :as => :signin

  root 'home#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	validates_format_of :email, :with => /^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/, multiline:true
	validates :title, presence: true
	validates :description, presence: true
	validates :location, presence: true
	validates :email, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :listings

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.password = "#{auth.info.name+'123'}"
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_use
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.all
    @user = current_user
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    @listing.save
    redirect_to '/'
  end

  def destroy
  end

  def update
  end

  def edit
  end

  def show
    @listing = Listing.find_by(id: params[:id])
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :description, :location, :email, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

	def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  before_filter :redirect_signed_in_users, only: [:create, :new]
  skip_before_filter :require_login, only: [:create, :new], raise: false
  skip_before_filter :authorize, only: [:create, :new], raise: false

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
  	name = user_params.delete(:name)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
    	user.name = name
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[:user] || Hash.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row">
	<div class="col-lg-4">
	</div>

	<div class="col-lg-4">
		<h1 class="text-center jumbotron">WELCOME HOME</h1>
		<p class="text-center">Rent unique places to stay from local hosts in 190+ countries.</p>

		<% if current_user %>
			<%= link_to "List a Property", new_listing_path, id: "new_listing" %>
			<%= link_to "Show all Properties", listings_path, id: "show_all_listing" %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pairbnb</a>
    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if Clearance.configuration.allow_sign_up? %>
            <%= link_to t(".sign_up"), sign_up_path %>
          <% end %>
        </li>
        <li>
        <% if current_user %>
          Welcome <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out"%>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button">Sign in<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Sign in from Facebook", "/auth/facebook", id: "sign_in"%></li>
              <li><%= link_to "Sign in using email", sign_in_path%></li>
            </ul>
          </li>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

     

    	<div id="user-widget">
        <% if current_user %>
          Welcome <strong><%= current_user.name %></strong>!
            <%= link_to "Sign out", signout_path, id: "sign_out"%>
          <%= link_to "Sign out", sign_out_path, method: :delete%>
        <% else %>
          <%= link_to "Sign in from Facebook", "/auth/facebook", id: "sign_in"%>
          <%= link_to "Sign in", sign_in_path%>
        <% end %>
      </div>

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>

<%= yield %>

</body>
</html>

app/views/listings/create.html.erb
<!-- <h1>Confirm your property!</h1>

<p>Your details are as follows:</p>

<ul>
	<li>Title: <%= @listing.title %></li>
	<li>Description: <%= @listing.description %></li>
	<li>Location: <%= @listing.location %></li>
	<li>Contact email: <%= @listing.email %></li>
</ul>

<div class="submit-field">

  	<button>Confirm<% @listing.save! %></button>


  <%= link_to new_listing_path do %>
  	<button>Cancel</button>
  <% end %>
</div> -->

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<h1>All Properties</h1>

<% @listings.each do |property| %>
	<ul>
		<li>
			<a href="/listings/<%=property.id%>"><%= property.title %> at <%= property.location %></a>
			<h5>Posted by: <%= property.user.name %></h5>
		</li>
	</ul>
<% end %>

app/views/listings/new.html.erb
<h1>Post your new property here!</h1>

<%= form_for @listing do |form| %>
  <div class="text-field">
    <%= form.label :title %>
    <%= form.text_field :title, type: 'title' %>
  </div>

  <div class="text-field">
    <%= form.label :description %>
    <%= form.text_field :description, type: 'description' %>
  </div>

  <div class="text-field">
    <%= form.label :location %>
    <%= form.text_field :location, type: 'location' %>
  </div>

	<div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>	

  <div class="submit-field">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/show.html.erb
<h1>Property</h1>

<ul>
	<li>Title: <%= @listing.title %></li>
	<li>Description: <%= @listing.description %></li>
	<li>Location: <%= @listing.location %></li>
	<li>Contact email: <%= @listing.email %></li>
</ul>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name, type: 'name' %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/create.html.erb
<h1>User#create</h1>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

  <% end %>
</div>




<!-- <h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name%><br>

  <%= f.label :email %>
  <%= f.email_field :email %><br>

  <%= f.label :password %>
  <%= f.password_field :encrypted_password %><br>

  <%= f.submit "Create my account" %>
<% end %> -->

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>